import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";

// Better Auth tables (user, session, account, verification), generated by the
// Better Auth CLI (`npx auth generate`). Regenerate after adding auth plugins
// that need tables; see README › Authentication.
export * from "./auth-schema";

// D1 is SQLite: store timestamps as epoch milliseconds, matching Better Auth.
const timestamp = (name: string) =>
  integer(name, { mode: "timestamp_ms" }).default(
    sql`(cast(unixepoch('subsecond') * 1000 as integer))`,
  );

// Example posts table with drizzle-zod integration
export const posts = sqliteTable("posts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  content: text("content").notNull(),
  status: text("status", { enum: ["draft", "published"] })
    .notNull()
    .default("draft"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
});

// Zod schemas generated from Drizzle schema
export const postIdSchema = z.object({ id: z.int().positive() });
export const selectPostSchema = createSelectSchema(posts);
export const insertPostSchema = createInsertSchema(posts);

// Types inferred from schemas
export type PostId = z.infer<typeof postIdSchema>;
export type Post = z.infer<typeof selectPostSchema>;
export type InsertPost = z.infer<typeof insertPostSchema>;
