/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExampleAccountRouteImport } from './routes/example/account'
import { Route as ExampleChatRouteImport } from './routes/example/chat'
import { Route as ExampleFormRouteImport } from './routes/example/form'
import { Route as ExampleRestApiRouteImport } from './routes/example/rest-api'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ExampleApiChatRouteImport } from './routes/example/api.chat'
import { Route as ExamplePostsIndexRouteImport } from './routes/example/posts/index'
import { Route as ExamplePostsPostIdRouteImport } from './routes/example/posts/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleAccountRoute = ExampleAccountRouteImport.update({
  id: '/example/account',
  path: '/example/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleChatRoute = ExampleChatRouteImport.update({
  id: '/example/chat',
  path: '/example/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleFormRoute = ExampleFormRouteImport.update({
  id: '/example/form',
  path: '/example/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRestApiRoute = ExampleRestApiRouteImport.update({
  id: '/example/rest-api',
  path: '/example/rest-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleApiChatRoute = ExampleApiChatRouteImport.update({
  id: '/example/api/chat',
  path: '/example/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplePostsIndexRoute = ExamplePostsIndexRouteImport.update({
  id: '/example/posts/',
  path: '/example/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplePostsPostIdRoute = ExamplePostsPostIdRouteImport.update({
  id: '/example/posts/$postId',
  path: '/example/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/example/account': typeof ExampleAccountRoute
  '/example/chat': typeof ExampleChatRoute
  '/example/form': typeof ExampleFormRoute
  '/example/rest-api': typeof ExampleRestApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof ExamplePostsPostIdRoute
  '/example/posts/': typeof ExamplePostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/example/account': typeof ExampleAccountRoute
  '/example/chat': typeof ExampleChatRoute
  '/example/form': typeof ExampleFormRoute
  '/example/rest-api': typeof ExampleRestApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof ExamplePostsPostIdRoute
  '/example/posts': typeof ExamplePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/example/account': typeof ExampleAccountRoute
  '/example/chat': typeof ExampleChatRoute
  '/example/form': typeof ExampleFormRoute
  '/example/rest-api': typeof ExampleRestApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof ExamplePostsPostIdRoute
  '/example/posts/': typeof ExamplePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/example/account'
    | '/example/chat'
    | '/example/form'
    | '/example/rest-api'
    | '/api/auth/$'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/example/account'
    | '/example/chat'
    | '/example/form'
    | '/example/rest-api'
    | '/api/auth/$'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/example/account'
    | '/example/chat'
    | '/example/form'
    | '/example/rest-api'
    | '/api/auth/$'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ExampleAccountRoute: typeof ExampleAccountRoute
  ExampleChatRoute: typeof ExampleChatRoute
  ExampleFormRoute: typeof ExampleFormRoute
  ExampleRestApiRoute: typeof ExampleRestApiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ExampleApiChatRoute: typeof ExampleApiChatRoute
  ExamplePostsPostIdRoute: typeof ExamplePostsPostIdRoute
  ExamplePostsIndexRoute: typeof ExamplePostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/account': {
      id: '/example/account'
      path: '/example/account'
      fullPath: '/example/account'
      preLoaderRoute: typeof ExampleAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/chat': {
      id: '/example/chat'
      path: '/example/chat'
      fullPath: '/example/chat'
      preLoaderRoute: typeof ExampleChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/form': {
      id: '/example/form'
      path: '/example/form'
      fullPath: '/example/form'
      preLoaderRoute: typeof ExampleFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/rest-api': {
      id: '/example/rest-api'
      path: '/example/rest-api'
      fullPath: '/example/rest-api'
      preLoaderRoute: typeof ExampleRestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/api/chat': {
      id: '/example/api/chat'
      path: '/example/api/chat'
      fullPath: '/example/api/chat'
      preLoaderRoute: typeof ExampleApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/posts/': {
      id: '/example/posts/'
      path: '/example/posts'
      fullPath: '/example/posts/'
      preLoaderRoute: typeof ExamplePostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/posts/$postId': {
      id: '/example/posts/$postId'
      path: '/example/posts/$postId'
      fullPath: '/example/posts/$postId'
      preLoaderRoute: typeof ExamplePostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ExampleAccountRoute: ExampleAccountRoute,
  ExampleChatRoute: ExampleChatRoute,
  ExampleFormRoute: ExampleFormRoute,
  ExampleRestApiRoute: ExampleRestApiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ExampleApiChatRoute: ExampleApiChatRoute,
  ExamplePostsPostIdRoute: ExamplePostsPostIdRoute,
  ExamplePostsIndexRoute: ExamplePostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
