/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExampleAccountRouteImport } from './routes/_app/example/account'
import { Route as AppExampleChatRouteImport } from './routes/_app/example/chat'
import { Route as AppExampleFormRouteImport } from './routes/_app/example/form'
import { Route as AppExampleRestApiRouteImport } from './routes/_app/example/rest-api'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ExampleApiChatRouteImport } from './routes/example/api.chat'
import { Route as AppExamplePostsIndexRouteImport } from './routes/_app/example/posts/index'
import { Route as AppExamplePostsPostIdRouteImport } from './routes/_app/example/posts/$postId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExampleAccountRoute = AppExampleAccountRouteImport.update({
  id: '/example/account',
  path: '/example/account',
  getParentRoute: () => AppRoute,
} as any)
const AppExampleChatRoute = AppExampleChatRouteImport.update({
  id: '/example/chat',
  path: '/example/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppExampleFormRoute = AppExampleFormRouteImport.update({
  id: '/example/form',
  path: '/example/form',
  getParentRoute: () => AppRoute,
} as any)
const AppExampleRestApiRoute = AppExampleRestApiRouteImport.update({
  id: '/example/rest-api',
  path: '/example/rest-api',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleApiChatRoute = ExampleApiChatRouteImport.update({
  id: '/example/api/chat',
  path: '/example/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExamplePostsIndexRoute = AppExamplePostsIndexRouteImport.update({
  id: '/example/posts/',
  path: '/example/posts/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamplePostsPostIdRoute = AppExamplePostsPostIdRouteImport.update({
  id: '/example/posts/$postId',
  path: '/example/posts/$postId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/example/account': typeof AppExampleAccountRoute
  '/example/chat': typeof AppExampleChatRoute
  '/example/form': typeof AppExampleFormRoute
  '/example/rest-api': typeof AppExampleRestApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof AppExamplePostsPostIdRoute
  '/example/posts/': typeof AppExamplePostsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/example/account': typeof AppExampleAccountRoute
  '/example/chat': typeof AppExampleChatRoute
  '/example/form': typeof AppExampleFormRoute
  '/example/rest-api': typeof AppExampleRestApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/example/posts/$postId': typeof AppExamplePostsPostIdRoute
  '/example/posts': typeof AppExamplePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/example/account': typeof AppExampleAccountRoute
  '/_app/example/chat': typeof AppExampleChatRoute
  '/_app/example/form': typeof AppExampleFormRoute
  '/_app/example/rest-api': typeof AppExampleRestApiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/example/api/chat': typeof ExampleApiChatRoute
  '/_app/example/posts/$postId': typeof AppExamplePostsPostIdRoute
  '/_app/example/posts/': typeof AppExamplePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/example/account'
    | '/example/chat'
    | '/example/form'
    | '/example/rest-api'
    | '/api/auth/$'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/example/account'
    | '/example/chat'
    | '/example/form'
    | '/example/rest-api'
    | '/api/auth/$'
    | '/example/api/chat'
    | '/example/posts/$postId'
    | '/example/posts'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/example/account'
    | '/_app/example/chat'
    | '/_app/example/form'
    | '/_app/example/rest-api'
    | '/api/auth/$'
    | '/example/api/chat'
    | '/_app/example/posts/$postId'
    | '/_app/example/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ExampleApiChatRoute: typeof ExampleApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/example/account': {
      id: '/_app/example/account'
      path: '/example/account'
      fullPath: '/example/account'
      preLoaderRoute: typeof AppExampleAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/example/chat': {
      id: '/_app/example/chat'
      path: '/example/chat'
      fullPath: '/example/chat'
      preLoaderRoute: typeof AppExampleChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/example/form': {
      id: '/_app/example/form'
      path: '/example/form'
      fullPath: '/example/form'
      preLoaderRoute: typeof AppExampleFormRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/example/rest-api': {
      id: '/_app/example/rest-api'
      path: '/example/rest-api'
      fullPath: '/example/rest-api'
      preLoaderRoute: typeof AppExampleRestApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/api/chat': {
      id: '/example/api/chat'
      path: '/example/api/chat'
      fullPath: '/example/api/chat'
      preLoaderRoute: typeof ExampleApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/example/posts/': {
      id: '/_app/example/posts/'
      path: '/example/posts'
      fullPath: '/example/posts/'
      preLoaderRoute: typeof AppExamplePostsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/example/posts/$postId': {
      id: '/_app/example/posts/$postId'
      path: '/example/posts/$postId'
      fullPath: '/example/posts/$postId'
      preLoaderRoute: typeof AppExamplePostsPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppExampleAccountRoute: typeof AppExampleAccountRoute
  AppExampleChatRoute: typeof AppExampleChatRoute
  AppExampleFormRoute: typeof AppExampleFormRoute
  AppExampleRestApiRoute: typeof AppExampleRestApiRoute
  AppExamplePostsPostIdRoute: typeof AppExamplePostsPostIdRoute
  AppExamplePostsIndexRoute: typeof AppExamplePostsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppExampleAccountRoute: AppExampleAccountRoute,
  AppExampleChatRoute: AppExampleChatRoute,
  AppExampleFormRoute: AppExampleFormRoute,
  AppExampleRestApiRoute: AppExampleRestApiRoute,
  AppExamplePostsPostIdRoute: AppExamplePostsPostIdRoute,
  AppExamplePostsIndexRoute: AppExamplePostsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ExampleApiChatRoute: ExampleApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
